
# Here is a useful link if you want to override autogenerated models: https://github.com/PixiGeko/Minecraft-default-assets/tree/latest/assets/minecraft/models/block

# Import database helper and setup constants
from python_datapack.utils.database_helper import *
from python_datapack.utils.ingredients import *
from python_datapack.constants import *

# Configuration to generate everything about the material based on "steel_ingot"
ORES_CONFIGS: dict[str, EquipmentsConfig|None] = {
    "steel_ingot":	EquipmentsConfig(
        # This steel is equivalent to iron,
        equivalent_to = DEFAULT_ORE.IRON,

        # But, has more durability (3 times more)
        pickaxe_durability = 3 * VanillaEquipments.PICKAXE.value[DEFAULT_ORE.IRON]["durability"],

        # And, does 1 more damage per hit (mainhand), and has 0.5 more armor, and mines 20% faster (pickaxe)
        attributes = {"attack_damage": 1, "armor": 0.5, "mining_efficiency": 0.2}
    ),

    # Simple material stone, this will automatically detect stone stick and rod textures.
    "minecraft:stone": None,
}

# Main function should return a database
def main(config: dict) -> dict[str, dict]:
    database: dict[str,dict] = {}
    namespace: str = config["namespace"]

    # Generate ores in database (add every stuff (found in the textures folder) related to the given materials, to the database)
    generate_everything_about_these_materials(config, database, ORES_CONFIGS)

    # Generate custom disc records
    generate_custom_records(config, database, "auto")

    # Final adjustments, you definitively should keep them!
    add_item_model_component(config, database)
    add_item_name_and_lore_if_missing(config, database)
    add_private_custom_data_for_namespace(config, database)
    add_smithed_ignore_vanilla_behaviours_convention(database)

    # Return database
    return database

